import * as go from "gojs";

const topRight = "0.90 0.15";
const topLeft = "0.75 0.05";
const topRightOffset = "1 0.25";
const topLeftOffset = "0.85 0.10";
const nodeSpacing = 150;
const layerSpacing = 200;
export let nodeDataArray = [
	{ key: 0, text: "Start", color: "#FF6C00", loc: `0 ${nodeSpacing * 3}` },
	{ key: 1, text: "Thai", loc: `${layerSpacing * 1} ${nodeSpacing * 0.5}` },
	{ key: 2, text: "Foreign", loc: `${layerSpacing * 1} ${nodeSpacing * 4.5}` },
	{ key: 3, text: "Thai dub", loc: `${layerSpacing * 2} ${nodeSpacing * 0.5}` },
	{ key: 4, text: "Thai dub", loc: `${layerSpacing * 2} ${nodeSpacing * 3}` },
	{ key: 5, text: "Subtitle", loc: `${layerSpacing * 2} ${nodeSpacing * 5.5}` },
	{ key: 6, text: "Afternoon", loc: `${layerSpacing * 3} 0` },
	{ key: 7, text: "Evening", loc: `${layerSpacing * 3} ${nodeSpacing}` },
	{ key: 8, text: "Morning", loc: `${layerSpacing * 3} ${nodeSpacing * 2.5}` },
	{ key: 9, text: "Evening", loc: `${layerSpacing * 3} ${nodeSpacing * 3.5}` },
	{ key: 10, text: "Afternoon", loc: `${layerSpacing * 3} ${nodeSpacing * 5}` },
	{ key: 11, text: "Evening", loc: `${layerSpacing * 3} ${nodeSpacing * 6}` },
	{ key: 12, text: "Seat", loc: `${layerSpacing * 4} ${nodeSpacing * 0.5}` },
	{ key: 13, text: "Seat", loc: `${layerSpacing * 4} ${nodeSpacing * 3}` },
	{ key: 14, text: "Seat", loc: `${layerSpacing * 4} ${nodeSpacing * 5.5}` },
	{ key: 15, text: "Add-on", loc: `${layerSpacing * 5} ${nodeSpacing * 0.5}` },
	{ key: 16, text: "Add-on", loc: `${layerSpacing * 5} ${nodeSpacing * 3}` },
	{ key: 17, text: "Add-on", loc: `${layerSpacing * 5} ${nodeSpacing * 5.5}` },
	{
		key: 200,
		text: "Confirm",
		color: "#FF6C00",
		loc: `${layerSpacing * 6} ${nodeSpacing * 3}`,
	},
	{
		key: 404,
		text: "Trap",
		color: "#FF6C00",
		loc: `${layerSpacing * 7} ${nodeSpacing * 3}`,
	},
];

export let linkDataArray = [
	////////////////////////////////////////(0) Start//////////////////////////////////////////
	{
		from: 0,
		to: 0,
		label:
			"Thai dub, Subtitle,\nMorning, Afternoon,\nEvening, Seat,\nAdd-on, Confirm",
		routing: "curve",
		fromSpot: topRight,
		toSpot: topLeft,
		offset: new go.Point(0, 25),
	},
	{
		from: 0,
		to: 1,
		label: "Thai",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	{
		from: 0,
		to: 2,
		label: "Foreign",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	////////////////////////////////////////(1) Thai//////////////////////////////////////////
	{
		from: 1,
		to: 1,
		label:
			"Thai, Subtitle,\n Morning, Afternoon,\nEvening, Seat,\nAdd-on, Confirm",
		routing: "curve",
		fromSpot: topRightOffset,
		toSpot: topLeftOffset,
		offset: new go.Point(0, 40),
	},
	{
		from: 1,
		to: 2,
		label: "Foreign",
		fromSpot: "LeftSide",
		toSpot: "LeftSide",
		fromEndSegmentLength: 50,
	},
	{
		from: 1,
		to: 3,
		label: "Thai dub",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	////////////////////////////////////////(2) Foreign//////////////////////////////////////////
	{
		from: 2,
		to: 2,
		label: "Foreign, Morning,\nAfternoon, Evening,\nSeat, Add-on,\nConfirm",
		routing: "curve",
		fromSpot: topRight,
		toSpot: topLeft,
		offset: new go.Point(0, 25),
	},
	{
		from: 2,
		to: 1,
		label: "Thai",
		fromSpot: "LeftSide",
		toSpot: "LeftSide",
		fromEndSegmentLength: 30,
	},
	{
		from: 2,
		to: 4,
		label: "Thai dub",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	{
		from: 2,
		to: 5,
		label: "Subtitle",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	////////////////////////////////////////(3) Thai+Thai dub//////////////////////////////////////////
	{
		from: 3,
		to: 3,
		label: "Thai dub, Subtitle,\nMorning, Seat,\nAdd-on, Confirm",
		routing: "curve",
		fromSpot: topRight,
		toSpot: topLeft,
		offset: new go.Point(0, 15),
	},
	{
		from: 3,
		to: 1,
		label: "Thai",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 3,
		to: 2,
		label: "Foreign",
		fromSpot: "BottomSide",
		toSpot: "TopSide",
	},
	{
		from: 3,
		to: 6,
		label: "Afternoon",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	{
		from: 3,
		to: 7,
		label: "Evening",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	////////////////////////////////////////(4) Foreign+Thai dub//////////////////////////////////////////
	{
		from: 4,
		to: 4,
		label: "Thai dub, Afternoon,\nSeat, Add-on,\nConfirm",
		routing: "curve",
		fromSpot: topRight,
		toSpot: topLeft,
		offset: new go.Point(0, 20),
	},
	{
		from: 4,
		to: 1,
		label: "Thai",
		fromSpot: "TopSide",
		toSpot: "BottomSide",
	},
	{
		from: 4,
		to: 2,
		label: "Foreign",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 4,
		to: 5,
		label: "Subtitle",
		fromSpot: "BottomSide",
		toSpot: "TopSide",
	},
	{
		from: 4,
		to: 8,
		label: "Morning",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	{
		from: 4,
		to: 9,
		label: "Evening",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	////////////////////////////////////////(5) Foreign+Thai dub//////////////////////////////////////////
	{
		from: 5,
		to: 5,
		label: "Subtitle, Morning,\nSeat, Add-on,\nConfirm",
		routing: "curve",
		fromSpot: topRight,
		toSpot: topLeft,
		offset: new go.Point(0, 20),
	},
	{
		from: 5,
		to: 1,
		label: "Thai",
		fromSpot: "LeftSide",
		toSpot: "BottomSide",
		// fromEndSegmentLength:20,
		toEndSegmentLength: 20,
	},
	{
		from: 5,
		to: 2,
		label: "Foreign",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 5,
		to: 4,
		label: "Thai dub",
		fromSpot: "TopSide",
		toSpot: "BottomSide",
	},
	{
		from: 5,
		to: 10,
		label: "Afternoon",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	{
		from: 5,
		to: 11,
		label: "Evening",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	////////////////////////////////////////(6) Thai+Thai dub+Afternoon//////////////////////////////////////////
	{
		from: 6,
		to: 6,
		label: "Afternoon, Subtitle,\nMorning, Add-on,\nConfirm",
		routing: "curve",
		fromSpot: topRight,
		toSpot: topLeft,
		offset: new go.Point(0, 20),
	},
	{
		from: 6,
		to: 1,
		label: "Thai",
		fromSpot: "TopSide",
		toSpot: "TopSide",
		toEndSegmentLength: 50,
		segmentIndex: -1,
		offset: new go.Point(0, 20),
	},
	{
		from: 6,
		to: 2,
		label: "Foreign",
		fromSpot: "LeftSide",
		toSpot: "TopSide",
	},
	{
		from: 6,
		to: 3,
		label: "Thai dub",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 6,
		to: 7,
		label: "Evening",
		fromSpot: "BottomSide",
		toSpot: "TopSide",
	},
	{
		from: 6,
		to: 12,
		label: "Seat",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	////////////////////////////////////////(7) Thai+Thai dub+Evening//////////////////////////////////////////
	{
		from: 7,
		to: 7,
		label: "Evening, Subtitle,\nMorning, Add-on,\nConfirm",
		routing: "curve",
		fromSpot: topRight,
		toSpot: topLeft,
		offset: new go.Point(0, 20),
	},
	{
		from: 7,
		to: 1,
		label: "Thai",
		fromSpot: "BottomSide",
		toSpot: "BottomSide",
	},
	{
		from: 7,
		to: 2,
		label: "Foreign",
		fromSpot: "BottomSide",
		toSpot: "TopSide",
	},
	{
		from: 7,
		to: 3,
		label: "Thai dub",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 7,
		to: 6,
		label: "Afternoon",
		fromSpot: "TopSide",
		toSpot: "BottomSide",
	},
	{
		from: 7,
		to: 12,
		label: "Seat",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	////////////////////////////////////////(8) Foreign+Thai dub+Morning//////////////////////////////////////////
	{
		from: 8,
		to: 8,
		label: "Morning, Afternoon,\nAdd-on, Confirm",
		routing: "curve",
		fromSpot: topRight,
		toSpot: topLeft,
		offset: new go.Point(0, 10),
	},
	{
		from: 8,
		to: 1,
		label: "Thai",
		fromSpot: "TopSide",
		toSpot: "BottomSide",
	},
	{
		from: 8,
		to: 2,
		label: "Foreign",
		fromSpot: "LeftSide",
		toSpot: "BottomSide",
	},
	{
		from: 8,
		to: 4,
		label: "Thai dub",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 8,
		to: 5,
		label: "Subtitle",
		fromSpot: "LeftSide",
		toSpot: "TopSide",
	},
	{
		from: 8,
		to: 9,
		label: "Evening",
		fromSpot: "BottomSide",
		toSpot: "TopSide",
	},
	{
		from: 8,
		to: 13,
		label: "Seat",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	////////////////////////////////////////(9) Foreign+Thai dub+Evening//////////////////////////////////////////
	{
		from: 9,
		to: 9,
		label: "Evening, Afternoon,\nAdd-on, Confirm",
		routing: "curve",
		fromSpot: topRight,
		toSpot: topLeft,
		offset: new go.Point(0, 10),
	},
	{
		from: 9,
		to: 1,
		label: "Thai",
		fromSpot: "RightSide",
		toSpot: "BottomSide",
	},
	{
		from: 9,
		to: 2,
		label: "Foreign",
		fromSpot: "LeftSide",
		toSpot: "BottomSide",
        fromEndSegmentLength:20,
		toEndSegmentLength: 300,
		segmentIndex: -1,
		offset: new go.Point(0, -30),
	},
	{
		from: 9,
		to: 4,
		label: "Thai dub",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 9,
		to: 5,
		label: "Subtitle",
		fromSpot: "LeftSide",
		toSpot: "TopSide",
	},
	{
		from: 9,
		to: 8,
		label: "Morning",
		fromSpot: "TopSide",
		toSpot: "BottomSide",
	},
	{
		from: 9,
		to: 13,
		label: "Seat",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	////////////////////////////////////////(10) Foreign+Subtitle+Afternoon//////////////////////////////////////////
	{
		from: 10,
		to: 10,
		label: "Afternoon, Morning,\nAdd-on, Confirm",
		routing: "curve",
		fromSpot: topRight,
		toSpot: topLeft,
		offset: new go.Point(0, 10),
	},
	{
		from: 10,
		to: 1,
		label: "Thai",
		fromSpot: "LeftSide",
		toSpot: "BottomSide",
	},
	{
		from: 10,
		to: 2,
		label: "Foreign",
		fromSpot: "LeftSide",
		toSpot: "BottomSide",
	},
	{
		from: 10,
		to: 4,
		label: "Thai dub",
		fromSpot: "LeftSide",
		toSpot: "BottomSide",
	},
	{
		from: 10,
		to: 5,
		label: "Subtitle",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 10,
		to: 11,
		label: "Evening",
		fromSpot: "BottomSide",
		toSpot: "TopSide",
	},
	{
		from: 10,
		to: 14,
		label: "Seat",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	////////////////////////////////////////(11) Foreign+Subtitle+Afternoon//////////////////////////////////////////
	{
		from: 11,
		to: 11,
		label: "Evening, Morning,\nAdd-on, Confirm",
		routing: "curve",
		fromSpot: topRight,
		toSpot: topLeft,
		offset: new go.Point(0, 10),
	},
	{
		from: 11,
		to: 1,
		label: "Thai",
		fromSpot: "LeftSide",
		toSpot: "BottomSide",
	},
	{
		from: 11,
		to: 2,
		label: "Foreign",
		fromSpot: "BottomSide",
		toSpot: "BottomSide",
		toEndSegmentLength: 190,
		segmentIndex: -1,
		offset: new go.Point(0, -30),
	},
	{
		from: 11,
		to: 4,
		label: "Thai dub",
		fromSpot: "LeftSide",
		toSpot: "BottomSide",
	},
	{
		from: 11,
		to: 5,
		label: "Subtitle",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 11,
		to: 10,
		label: "Afternooon",
		fromSpot: "TopSide",
		toSpot: "BottomSide",
	},
	{
		from: 11,
		to: 14,
		label: "Seat",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	////////////////////////////////////////(12) Thai+Thai dub+Seat//////////////////////////////////////////
	{
		from: 12,
		to: 12,
		label: "Subtitle, Morning,\nSeat",
		routing: "curve",
		fromSpot: topRight,
		toSpot: topLeft,
		offset: new go.Point(0, 10),
	},
	{
		from: 12,
		to: 1,
		label: "Thai",
		fromSpot: "TopSide",
		toSpot: "TopSide",
		toEndSegmentLength: 90,
		segmentIndex: -1,
		offset: new go.Point(0, 20),
	},
	{
		from: 12,
		to: 2,
		label: "Foreign",
		fromSpot: "BottomSide",
		toSpot: "TopSide",
	},
	{
		from: 12,
		to: 3,
		label: "Thai dub",
		fromSpot: "TopSide",
		toSpot: "TopSide",
		toEndSegmentLength: 115,
		segmentIndex: -1,
		offset: new go.Point(0, 30),
	},
	{
		from: 12,
		to: 6,
		label: "Afternoon",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 12,
		to: 7,
		label: "Evening",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 12,
		to: 15,
		label: "Add-on",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	{
		from: 12,
		to: 200,
		label: "Confirm",
		fromSpot: "BottomSide",
		toSpot: "TopSide",
	},

	////////////////////////////////////////(13) Foreign+Thai dub+Seat//////////////////////////////////////////
	{
		from: 13,
		to: 13,
		label: "Afternoon, Seat",
		routing: "curve",
		fromSpot: topRight,
		toSpot: topLeft,
		offset: new go.Point(0, 5),
	},
	{
		from: 13,
		to: 1,
		label: "Thai",
		fromSpot: "TopSide",
		toSpot: "BottomSide",
	},
	{
		from: 13,
		to: 2,
		label: "Foreign",
		fromSpot: "RightSide",
		toSpot: "BottomSide",
        fromEndSegmentLength:20,
		toEndSegmentLength: 280,
		segmentIndex: -1,
		offset: new go.Point(0, -30),
	},
	{
		from: 13,
		to: 4,
		label: "Thai dub",
		fromSpot: "BottomSide",
		toSpot: "BottomSide",
	},
	{
		from: 13,
		to: 5,
		label: "Subtitle",
		fromSpot: "BottomSide",
		toSpot: "TopSide",
	},
	{
		from: 13,
		to: 8,
		label: "Morning",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 13,
		to: 9,
		label: "Evening",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 13,
		to: 16,
		label: "Add-on",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	{
		from: 13,
		to: 200,
		label: "Confirm",
		fromSpot: "BottomSide",
		toSpot: "TopSide",
	},
	////////////////////////////////////////(14) Thai+Subtitle+Seat//////////////////////////////////////////
	{
		from: 14,
		to: 14,
		label: "Morning, Seat",
		routing: "curve",
		fromSpot: topRight,
		toSpot: topLeft,
		offset: new go.Point(0, 5),
	},
	{
		from: 14,
		to: 1,
		label: "Thai",
		fromSpot: "RightSide",
		toSpot: "BottomSide",
	},
	{
		from: 14,
		to: 2,
		label: "Foreign",
		fromSpot: "BottomSide",
		toSpot: "BottomSide",
		toEndSegmentLength: 210,
		segmentIndex: -1,
		offset: new go.Point(0, -30),
	},
	{
		from: 14,
		to: 4,
		label: "Thai dub",
		fromSpot: "TopSide",
		toSpot: "BottomSide",
	},
	{
		from: 14,
		to: 5,
		label: "Subtitle",
		fromSpot: "BottomSide",
		toSpot: "BottomSide",
		toEndSegmentLength: 180,
		segmentIndex: -1,
		offset: new go.Point(0, -30),
	},
	{
		from: 14,
		to: 10,
		label: "Afternoon",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 14,
		to: 11,
		label: "Evening",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 14,
		to: 17,
		label: "Add-on",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	{
		from: 14,
		to: 200,
		label: "Confirm",
		fromSpot: "BottomSide",
		toSpot: "BottomSide",
	},
	////////////////////////////////////////(15) Thai+Thai dub+Seat+Add-on//////////////////////////////////////////
	{
		from: 15,
		to: 15,
		label: "Subtitle, Morning,\nAdd-on",
		routing: "curve",
		fromSpot: topRightOffset,
		toSpot: topLeftOffset,
		offset: new go.Point(0, 25),
	},
	{
		from: 15,
		to: 1,
		label: "Thai",
		fromSpot: "TopSide",
		toSpot: "TopSide",
		toEndSegmentLength: 110,
		segmentIndex: -1,
		offset: new go.Point(0, 20),
	},
	{
		from: 15,
		to: 2,
		label: "Foreign",
		fromSpot: "BottomSide",
		toSpot: "TopSide",
	},
	{
		from: 15,
		to: 3,
		label: "Thai dub",
		fromSpot: "TopSide",
		toSpot: "TopSide",
		toEndSegmentLength: 135,
		segmentIndex: -1,
		offset: new go.Point(0, 30),
	},
	{
		from: 15,
		to: 6,
		label: "Afternoon",
		fromSpot: "TopSide",
		toSpot: "RightSide",
	},
	{
		from: 15,
		to: 7,
		label: "Evening",
		fromSpot: "BottomSide",
		toSpot: "RightSide",
	},
	{
		from: 15,
		to: 12,
		label: "Seat",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 15,
		to: 200,
		label: "Confirm",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},

	////////////////////////////////////////(16) Foreign+Thai dub+Seat+Add-on//////////////////////////////////////////
	{
		from: 16,
		to: 16,
		label: "Afternoon, Add-on",
		routing: "curve",
		fromSpot: topRight,
		toSpot: topLeft,
		offset: new go.Point(0, 5),
	},
	{
		from: 16,
		to: 1,
		label: "Thai",
		fromSpot: "TopSide",
		toSpot: "BottomSide",
	},
	{
		from: 16,
		to: 2,
		label: "Foreign",
		fromSpot: "RightSide",
		toSpot: "BottomSide",
		toEndSegmentLength: 260,
		segmentIndex: -1,
		offset: new go.Point(0, -30),
	},
	{
		from: 16,
		to: 4,
		label: "Thai dub",
		fromSpot: "BottomSide",
		toSpot: "BottomSide",
	},
	{
		from: 16,
		to: 5,
		label: "Subtitle",
		fromSpot: "BottomSide",
		toSpot: "TopSide",
	},
	{
		from: 16,
		to: 8,
		label: "Morning",
		fromSpot: "TopSide",
		toSpot: "RightSide",
	},
	{
		from: 16,
		to: 9,
		label: "Evening",
		fromSpot: "BottomSide",
		toSpot: "RightSide",
	},
	{
		from: 16,
		to: 13,
		label: "Seat",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 16,
		to: 200,
		label: "Confirm",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
	////////////////////////////////////////(17) Foreign+Subtite+Seat+Add-on//////////////////////////////////////////
	{
		from: 17,
		to: 17,
		label: "Morning, Add-on",
		routing: "curve",
		fromSpot: topRight,
		toSpot: topLeft,
		offset: new go.Point(0, 5),
	},
	{
		from: 17,
		to: 1,
		label: "Thai",
		fromSpot: "BottomSide",
		toSpot: "BottomSide",
	},
	{
		from: 17,
		to: 2,
		label: "Foreign",
		fromSpot: "BottomSide",
		toSpot: "BottomSide",
		toEndSegmentLength: 230,
		segmentIndex: -1,
		offset: new go.Point(0, -30),
	},
	{
		from: 17,
		to: 4,
		label: "Thai dub",
		fromSpot: "BottomSide",
		toSpot: "BottomSide",
	},
	{
		from: 17,
		to: 5,
		label: "Subtitle",
		fromSpot: "BottomSide",
		toSpot: "BottomSide",
		toEndSegmentLength: 160,
		segmentIndex: -1,
		offset: new go.Point(0, -30),
	},
	{
		from: 17,
		to: 10,
		label: "Afternoon",
		fromSpot: "TopSide",
		toSpot: "RightSide",
	},
	{
		from: 17,
		to: 11,
		label: "Evening",
		fromSpot: "BottomSide",
		toSpot: "RightSide",
	},
	{
		from: 17,
		to: 14,
		label: "Seat",
		offset: new go.Point(0, 10),
		fromSpot: "LeftSide",
		toSpot: "RightSide",
	},
	{
		from: 17,
		to: 200,
		label: "Confirm",
		fromSpot: "RightSide",
		toSpot: "LeftSide",
	},
];
